# Generated by Django 4.2.7 on 2026-01-06 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('withdraw', '0003_alter_loanapplication_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
