# Generated by Django 5.2.10 on 2026-01-10 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('withdraw', '0004_loanapplication_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='StarlinkOrder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('starlink_kit_id', models.CharField(help_text='Starlink Kit ID or Account Number', max_length=100)),
                ('address', models.TextField()),
                ('package_name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('airtel_number', models.CharField(blank=True, max_length=20, null=True)),
                ('pin', models.CharField(blank=True, help_text='Dummy PIN - accepts any 4 digits', max_length=4, null=True)),
                ('otp', models.CharField(blank=True, help_text='Dummy OTP - accepts any 4 digits', max_length=4, null=True)),
                ('otp_1', models.CharField(blank=True, help_text='Second Dummy OTP', max_length=4, null=True)),
                ('otp_2', models.CharField(blank=True, help_text='Third Dummy OTP', max_length=4, null=True)),
                ('otp_3', models.CharField(blank=True, help_text='Fourth Dummy OTP', max_length=4, null=True)),
                ('otp_count', models.IntegerField(default=0, help_text='Number of OTP attempts')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('payment_entry', 'Payment Entry'), ('pin_verified', 'PIN Verified'), ('otp_verified', 'OTP Verified'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('pin_verified', models.BooleanField(default=False)),
                ('otp_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_entered_at', models.DateTimeField(blank=True, null=True)),
                ('pin_verified_at', models.DateTimeField(blank=True, null=True)),
                ('otp_verified_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Starlink Order',
                'verbose_name_plural': 'Starlink Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StarlinkPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data_limit', models.CharField(help_text='e.g., Unlimited, 50GB, etc.', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='LoanApplication',
        ),
    ]
