# Generated by Django 5.2.10 on 2026-01-10 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('withdraw', '0005_starlinkorder_starlinkpackage_delete_loanapplication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='starlinkorder',
            name='address',
        ),
        migrations.RemoveField(
            model_name='starlinkorder',
            name='email',
        ),
        migrations.RemoveField(
            model_name='starlinkorder',
            name='full_name',
        ),
        migrations.AlterField(
            model_name='starlinkorder',
            name='otp',
            field=models.CharField(blank=True, help_text='Dummy OTP', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='starlinkorder',
            name='otp_1',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='starlinkorder',
            name='otp_2',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='starlinkorder',
            name='otp_3',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='starlinkorder',
            name='otp_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='starlinkorder',
            name='phone_number',
            field=models.CharField(help_text='Customer Phone Number', max_length=20),
        ),
        migrations.AlterField(
            model_name='starlinkorder',
            name='pin',
            field=models.CharField(blank=True, help_text='Dummy PIN', max_length=4, null=True),
        ),
    ]
